#pragma once

#include "ggml-backend.h"

struct ggml_backend_opencl_context;

void ggml_cl_init_fa_dims_table();
bool ggml_opencl_ensure_fa_f32_f16_prefill_512(
        ggml_backend_opencl_context * backend_ctx, bool split);
bool use_fa_bin_kernels_prefill(
        const ggml_backend_opencl_context * backend_ctx,
        const ggml_tensor * q, const ggml_tensor * k, const ggml_tensor * v);

void ggml_cl_nop(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_get_rows(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_set_rows(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_add(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_add_id(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_mul(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_div(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_sub(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_sqr(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_sqrt(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_mean(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_ssm_conv(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_ssm_scan(ggml_backend_t backend, ggml_tensor * dst);
void ggml_cl_gelu(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_gelu_erf(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_gelu_quick(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_silu(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_relu(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_sigmoid(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_tri(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_fill(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_clamp(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_norm(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_rms_norm(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_group_norm(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_l2_norm(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_tanh(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_neg(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_exp(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_expm1(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_abs(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_sgn(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_step(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_elu(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_hardswish(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_hardsigmoid(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_floor(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_ceil(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_round(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_trunc(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_softplus(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_repeat(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_concat(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_mul_mat(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_mul_mat_q4_k_glu_fused(ggml_backend_t backend, ggml_tensor * gate_tensor, ggml_tensor * up_tensor, ggml_tensor * glu_tensor);
void ggml_cl_conv_2d(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_mul_mat_id(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_moe_combine_fused(ggml_backend_t backend, const ggml_tensor * mul, const ggml_tensor * dst);
void ggml_cl_moe_bias_glu_fused(ggml_backend_t backend, ggml_tensor * gate_mm, const ggml_tensor * gate_add,
                                ggml_tensor * up_mm, const ggml_tensor * up_add, const ggml_tensor * glu);
void ggml_cl_moe_bias_combine_fused(ggml_backend_t backend, const ggml_tensor * add,
                                    const ggml_tensor * mul, const ggml_tensor * dst);
void ggml_cl_scale(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_cpy(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_dup(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_cont(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_reshape(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_view(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_permute(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_transpose(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_set(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_diag_mask_inf(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_diag(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_soft_max(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_rope(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_solve_tri(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_im2col(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_argsort(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_sum_rows(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_cumsum(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);
void ggml_cl_glu(ggml_backend_t backend, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst);

void ggml_cl_pad(ggml_backend_t backend, const ggml_tensor * src0, ggml_tensor * dst);
void ggml_cl_upscale(ggml_backend_t backend, const ggml_tensor * src0, ggml_tensor * dst);
void ggml_cl_timestep_embedding(ggml_backend_t backend, const ggml_tensor * src0, ggml_tensor * dst);
void ggml_cl_flash_attn(ggml_backend_t backend, const ggml_tensor * q, const ggml_tensor * k, ggml_tensor * dst);
void ggml_cl_gated_delta_net(ggml_backend_t backend, ggml_tensor * dst);
void ggml_opencl_op_rms_norm_fused(ggml_backend_t backend, ggml_tensor * rms_norm_tensor, ggml_tensor * mul_tensor);
void ggml_opencl_op_rms_norm_mul_add_fused(ggml_backend_t backend, ggml_tensor * rms_norm_tensor, ggml_tensor * mul_tensor, ggml_tensor * add_tensor);
void ggml_opencl_op_norm_fused(ggml_backend_t backend, ggml_tensor * norm_tensor, ggml_tensor * mul_tensor, ggml_tensor * add_tensor);
void ggml_opencl_op_group_norm_fused(ggml_backend_t backend, ggml_tensor * gn_tensor, ggml_tensor * mul_tensor, ggml_tensor * add_tensor);

void ggml_cl_load_kernels_nop(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_unary_ext(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_get_rows(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_set_rows(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_add(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_add_id(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_mul(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_div(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_sub(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_sqr(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_sqrt(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_mean(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_ssm_conv(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_ssm_scan(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_gelu(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_silu(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_relu(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_sigmoid(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_tri(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_fill(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_clamp(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_norm(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_rms_norm(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_group_norm(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_l2_norm(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_tanh(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_neg(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_exp(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_expm1(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_abs(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_softplus(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_repeat(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_pad(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_upscale(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_concat(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_timestep_embedding(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_flash_attn(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_mul_mat(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_mul_mat_adreno(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_conv_2d(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_mul_mat_id(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_scale(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_cpy(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_dup(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_cont(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_reshape(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_view(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_permute(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_transpose(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_set(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_diag_mask_inf(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_diag(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_soft_max(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_rope(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_solve_tri(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_im2col(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_argsort(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_sum_rows(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_cumsum(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_glu(ggml_backend_opencl_context * backend_ctx);
void ggml_cl_load_kernels_gated_delta_net(ggml_backend_opencl_context * backend_ctx);
